-- Row-Level Security — Inova Gastro 360
--
-- APLICADO VIA MIGRATION (spec 015):
--   packages/database/prisma/migrations/20260702160000_security_rls_billing/migration.sql
--
-- Este arquivo permanece apenas como referência histórica. Não executar manualmente.
--
-- Modelo:
--   - Policies por tenant usando app_current_tenant_id()
--     (contexto: SET LOCAL app.current_tenant_id — ver withTenant em
--      apps/workers/api-gateway/src/lib/db.ts)
--   - Role de aplicação `inova_gastro_app` criada NOLOGIN pela migration.
--     A senha é definida operacionalmente (nunca no repositório):
--       ALTER ROLE inova_gastro_app LOGIN PASSWORD '<segredo>';
--   - O owner das tabelas (migrations/seed) não sofre RLS; a API deve conectar
--     com inova_gastro_app em produção para o isolamento defense-in-depth.
